---
title: "Commitment and Corruption Exp1 - Figures"
author: "Simon van Baal"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(stargazer)
```



```{r Figures}

# The palette with black:
cbbPalette <-
  c(
    "#000000",
    "#E69F00",
    "#56B4E9",
    "#009E73",
    "#F0E442",
    "#0072B2",
    "#D55E00",
    "#CC79A7"
  )

## Plot dimensions
w = 6
h = 4

```

```{r Plot for different phases in exp 1}

## Here is an unused plot providing some insight to the fluctuating reports over the experiment.
Data <-
  Data %>%
  mutate(
    Phase = ifelse(Condition == "Collaborative", "Collaborative", "Individual"),
    Condition = factor(
      ifelse(
        Condition == "Pre-Collaborative",
        "Pre-Colab",
        ifelse(Condition == "Post-Collaborative",
               "Post-Colab",
               Condition)
      ),
      levels = c("Collaborative", "Pre-Colab", "Post-Colab")
    )
  )

IndividualReportPlot <- 
  ggplot(Data %>% filter(Condition != "Collaborative")) +
  aes(x = Report, fill = Condition) +
  geom_density(alpha = 0.4) +
  geom_hline(aes(yintercept = .167), linetype = "dashed") +
  scale_fill_manual(values = cbbPalette) +
  labs(x = "Die-roll Report", y = "Density") +
  scale_x_continuous(breaks = seq(1:6)) +
  theme_light()


FirstMoverReportPlot <- 
  ggplot(Data %>% filter(PlayerNo == "First Mover")) +
  aes(x = Report, fill = Phase) +
  geom_density(alpha = .4) +
  geom_hline(aes(yintercept = .167), linetype = "dashed") +
  scale_fill_manual(values = cbbPalette[6:7]) +
  labs(x = "Die-roll Report", y = " ") +
  theme_light() +
  scale_x_continuous(breaks = seq(1:6))

plotReportIndividualCollaborative <- 
  ggarrange(IndividualReportPlot, FirstMoverReportPlot, legend = "bottom")

plotReportIndividualCollaborative


```


```{r Plots}

barPlotFirstMoverData <-
  FirstMoverData %>% 
  group_by(Effort, Partnership) %>% 
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(
    Role = rep("First Mover"),
    Condition = factor(
      ifelse(
        Effort == "High Effort" &
          Partnership == "Long Partnership",
        "High Ef., Long Part.",
        ifelse(
          Effort == "Low Effort" &
            Partnership == "Long Partnership",
          "Low Ef., Long Part.",
          ifelse(
            Effort == "High Effort",
            "High Ef., Short Part.",
            "Low Ef., Short Part."
          )
        )
      ),
      levels = c(
        "Low Ef., Short Part.",
        "Low Ef., Long Part.",
        "High Ef., Short Part.",
        "High Ef., Long Part."
      )
    ),
    means = ifelse(
      Condition == "Low Ef., Short Part.",
      4.50,
      ifelse(
        Condition == "Low Ef., Long Part.",
        4.43,
        ifelse(Condition == "High Ef., Short Part.", 4.56, 4.51)
      )
    ),
    se = ifelse(
      Condition == "Low Ef., Short Part.",
      .145,
      ifelse(
        Condition == "Low Ef., Long Part.",
        .141,
        ifelse(Condition == "High Ef., Short Part.", .145, .137)
      )
    )
  )
barPlotSecondMoverData <-
  SecondMoverData %>% 
  group_by(Effort, Partnership) %>% 
  summarise(n = n()) %>%
  ungroup() %>%
  mutate(
    Role = rep("Second Mover"),
    Condition = factor(
      ifelse(
        Effort == "High Effort" &
          Partnership == "Long Partnership",
        "High Ef., Long Part.",
        ifelse(
          Effort == "Low Effort" &
            Partnership == "Long Partnership",
          "Low Ef., Long Part.",
          ifelse(
            Effort == "High Effort",
            "High Ef., Short Part.",
            "Low Ef., Short Part."
          )
        )
      ),
      levels = c(
        "Low Ef., Short Part.",
        "Low Ef., Long Part.",
        "High Ef., Short Part.",
        "High Ef., Long Part."
      )
    ),
    means = ifelse(
      Condition == "Low Ef., Short Part.",
      .472,
      ifelse(
        Condition == "Low Ef., Long Part.",
        .547,
        ifelse(Condition == "High Ef., Short Part.", .623, .541)
      )
    ),
    se = ifelse(
      Condition == "Low Ef., Short Part.",
      .0874,
      ifelse(
        Condition == "Low Ef., Long Part.",
        .0724,
        ifelse(Condition == "High Ef., Short Part.", .0909, .0799)
      )
    )
  )

barPlotData <-
  rbind(barPlotFirstMoverData, barPlotSecondMoverData) %>%
  mutate(
    ConditionNumeric = as.numeric(Condition),
    means = ifelse(Role == "Second Mover", means * 6, means),
    se = ifelse(Role == "Second Mover", se * 6, se)
  )


num = 6
ggplot(barPlotData %>%
         filter(Role == "First Mover"), aes(x = Condition)) +
  geom_bar(
    aes(x = ConditionNumeric - .15, y = means, fill = Role),
    stat = "identity",
    position = position_dodge(),
    alpha = .8,
    width = .3
  ) +
  geom_errorbar(
    data = barPlotData %>%
      filter(Role == "First Mover"),
    aes(
      x = ConditionNumeric - .15,
      ymin = means - se,
      y = means,
      ymax = means + se
    ),
    width = .1
  ) +
  geom_bar(
    data = barPlotData %>%
      filter(Role == "Second Mover"),
    aes(x = ConditionNumeric + .15, y = means, fill = Role),
    alpha = .8,
    stat = "identity",
    width = .3
  ) +
  geom_errorbar(
    data = barPlotData %>%
      filter(Role == "Second Mover"),
    aes(
      x = ConditionNumeric + .15,
      ymin = means - se,
      y = means,
      ymax = means + se
    ),
    width = .1
  ) +
  scale_y_continuous(
    limits = c(0, 6),
    # Features of the first axis
    name = "Report Magnitude",
    # Add a second axis and specify its features
    sec.axis = sec_axis( ~ . * (1 / num), name = "Proption of trials that are doubles")
  ) +
  scale_x_continuous(
    breaks = c(1, 2, 3, 4),
    labels = c(
      "High Ef., Short Part.",
      "Low Ef., Long Part. ",
      "High Ef., Short Part.",
      "High Ef., Long Part."
    )
                   ) +
  theme_light()
```



```{r Doubles analysis plots}

plotEmmeans <- 
  emmeans(glmmDouble, ~ Effort | Partnership, type = "response")
plotEmmeansReport <- 
  emmeans(lmmReport, 'Effort', by ='Partnership')
reportInteractionPlot <-
  plot(plotEmmeansReport,
     comparison = T, CIs = FALSE,
         horizontal = T
     ) +
  labs(x = "Report magnitude",
       y = "Condition") +
  scale_x_continuous(limits = c(1,6), breaks = c(1,2,3,4,5,6)) +
  theme_light() +
  geom_vline(xintercept = 3.5, col = "blue", linetype="dashed")

doubleInteractionPlot <- 
  plot(plotEmmeans,
     comparison = T, CIs = FALSE,
     horizontal = T
     ) +
  lims(x = c(0,1)) +
  labs(x = "Probability of a double",
       y = "Condition") +
  theme_light() +
  geom_vline(xintercept = 1/6, col = "blue", linetype="dashed")

InteractionPlots <-
  ggarrange(reportInteractionPlot, doubleInteractionPlot,
            nrow = 2)
ggsave("./figures/plot_exp1_interaction.png",
         height = 1.4*h, width = 1.6*w)

InteractionPlots
```


```{r plots Continued, echo = F}
## Creating a scatterplot of the reports by player 1 and player 2.

## Create a scatterplot for the expected behaviour in case of honesty
Random.1 <- sample(1:6, 1548, replace = TRUE)
Random.2 <- sample(1:6, 1548, replace = TRUE)
Random <- data.frame(Random.1, Random.2)
colnames(Random) <- c("Player.1", "Player.2")
rm(Random.1)
rm(Random.2)

plot.random <- ggplot(Random, 
       aes(Player.1, 
           Player.2)) +
  geom_point(size = 1, 
             shape = 1, 
             color = "blue",
             position = position_jitter(width = 0.45, height = 0.45)) + 
  scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6)) +
  coord_fixed(xlim = c(0.75, 6.25), ylim = c(0.75, 6.25)) +
  theme_bw(base_size = 8) + 
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black", size = 0.1)) +
  labs(title = "Expected",
       x = "First Mover", 
       y = "Second Mover") +
  geom_hline(yintercept = c(1.5, 2.5, 3.5, 4.5, 5.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 3.5, 4.5, 5.5))

plot.all <- 
  ggplot(SecondMoverData, 
       aes(ReportFirstMover, 
           Report)) +
  geom_point(size = 1, 
             shape = 1, 
             color = "blue",
             position = position_jitter(width = 0.45, height = 0.45)) + 
  scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6)) +
  coord_fixed(xlim = c(0.75, 6.25), ylim = c(0.75, 6.25)) +
  theme_bw(base_size = 8) + 
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black", size = 0.1)) +
  labs(title = "Experimental",
       x = "First Mover", 
       y = " ") +
  geom_hline(yintercept = c(1.5, 2.5, 3.5, 4.5, 5.5)) +
  geom_vline(xintercept = c(1.5, 2.5, 3.5, 4.5, 5.5))

(plotExpectedActual <- 
  ggarrange(plot.random, plot.all))
ggsave("./figures/plot_exp1_dot-plot-expected.png", width = 1.5*w, h = 1.1*h)

```


```{r Interaction dot plot}

###### New W&S plot

(plotInteractionDots <- 
  ggplot(SecondMoverData, 
       aes(ReportFirstMover, 
           Report)) +
           geom_point(size = 1.2, 
                      shape = 1, 
                      color = "blue",
                      position = position_jitter(width = 0.45, height = 0.45)) + 
       scale_x_continuous(breaks = c(1,2,3,4,5,6)) +
       scale_y_continuous(breaks = c(1,2,3,4,5,6)) +
       coord_fixed(xlim = c(0.75, 6.25), ylim = c(0.75, 6.25)) +
       theme_bw(base_size = 8) + 
       theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             axis.line = element_line(colour = "black", size = 0.1)) +
       labs(title = "Partnership by Effort",
            x = "First Mover's reports", 
            y = "Second Mover's reports") +
       geom_hline(yintercept = c(1.5, 2.5, 3.5, 4.5, 5.5)) +
       geom_vline(xintercept = c(1.5, 2.5, 3.5, 4.5, 5.5)) +
  facet_grid(Effort ~ Partnership))
ggsave("./figures/plot_exp1_interaction-dotplot.png")

```


```{r round number plot}

ggplot(FullData %>% 
  filter(PlayerNo == "First Mover", !is.na(Report)) %>% 
  mutate(Round = ifelse(round > 200, round - 200, 
                        ifelse(round > 100, round - 100, round))) %>%
  group_by(Condition, Round) %>% 
  summarise(ReportMean = mean(as.numeric(Report), na.rm = T), 
            se = sd(as.numeric(Report), na.rm = T)/n()),
  aes(x = Round, y = ReportMean, colour = Condition)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  scale_x_continuous(breaks = seq(0,36, 2)) +
  labs(x = 'Round number', y = 'Report magnitude', col = 'Block') +
  theme_light()

```

```{r individual v collaborative plot}
ggplot(Data %>% 
         filter(Condition != "Pre-Colab", PlayerNo == "First Mover"),
       aes(x = Report, fill = Condition)) +
  geom_density() +
  scale_fill_viridis_d(begin = .2, end = .7) +
  theme_light()
  


```

```{r regression table}
#### 

stargazer(glmmDouble, 
          type = "html", 
          out = "LMM.Table.htm", 
          ci = TRUE,
          intercept.bottom = FALSE,
          single.row = FALSE)

####################################


```
