---
title: "Commitment and Corruption Exp 2 - Figures"
author: "Simon van Baal"
date: '2022-06-27'
output: html_document
---

```{r setup}
library(ggplot2)
library(ggpubr)
library(stargazer)

```

```{r Interaction plots Exp2}

lmmReportExp2Plot <-
  mixed(
    Report ~ Effort * Rewards +
      (Effort + Rewards | ParticipantId),
    data = FirstMoverDataExp2 %>%
      mutate(
        Effort = ifelse(Effort == "HighEffort", "High", "Low"),
        Rewards = ifelse(
          Rewards == "FirstMover",
          "Own Rewards",
          ifelse(Rewards == "SecondMover", "Partner Rewards", "Joint Rewards")
        )
      )
  )


glmmDoubleExp2Plot <-
  mixed(
    Double ~ Effort * Rewards + 
      zcFirstMoverReport + 
      (Effort + Rewards + zcFirstMoverReport|ParticipantId),
    family = binomial(link = "logit"),
    method = "LRT",
    data = SecondMoverDataExp2 %>%
      mutate(
        Effort = ifelse(Effort == "HighEffort", "High", "Low"),
        Rewards = ifelse(
          Rewards == "FirstMover",
          "Partner Rewards",
          ifelse(Rewards == "SecondMover", "Own Rewards", "Joint Rewards")
        )
      )
  )

ReportInteractionEmm <-
  emmeans(lmmReportExp2Plot, specs = "Rewards", by = "Effort")
DoubleInteractionEmm <-
  emmeans(glmmDoubleExp2Plot, "Rewards", by = "Effort", type = "response")

```

```{r Plotting the models}

reportInteractionPlotExp2 <-
  plot(ReportInteractionEmm,
       comparison = T, CIs = FALSE,) +
  labs(x = "Report magnitude",
       y = "Condition") +
  scale_x_continuous(limits = c(1, 6), breaks = c(1, 2, 3, 4, 5, 6)) +
  theme_light()

doubleInteractionPlotExp2 <-
  plot(DoubleInteractionEmm,
       comparison = T, CIs = FALSE,) +
  lims(x = c(0, 1)) +
  labs(x = "Probability of a double",
       y = "Condition") +
  theme_light()

InteractionPlotsExp2 <-
  ggarrange(reportInteractionPlotExp2, doubleInteractionPlotExp2,
            nrow = 2)
ggsave(
  "./figures/plots_interaction_exp2.png",
  height = h * 1,
  width = w * 1.3
)

```